packages:
  - apps/*
  - libs/*
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  better-sqlite3: true
  esbuild: true
  nx: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
